spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_NAME:story}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:${KAFKA_IP}:19092}
    template:
      observation-enabled: false
    listener:
      observation-enabled: false
      ack-mode: manual

    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:${spring.application.name}-consumer-group}
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.earseo.story.common.KafkaEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        spring.json.add.type.headers: false
    properties:
      security.protocol: ${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:PLAINTEXT}
  data:
    redis:
      password: ${VALKEY_PASSWORD:valkeypass}
      sentinel:
        master: ${SPRING_DATA_REDIS_SENTINEL_MASTER:valkey-master}
        nodes: ${SPRING_DATA_REDIS_SENTINEL_NODES:localhost:26379,localhost:26380,localhost:26381}
      database: 6

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
logging:
  level:
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:debug}
    org.springframework.jdbc.core.JdbcTemplate: ${LOGGING_LEVEL_JDBC_TEMPLATE:debug}
cloud:
  aws:
    credentials:
      access-key: ${AWS_CREDENTAIL_ACCESS_KEY:acess_key}
      secret-key: ${AWS_CREDENTAIL_SECRET_KEY:secret_key}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S#_BUCKET:example-bucket}
    cloudfront:
      domain: ${AWS_CLOUDFRONT_DOMAIN:cdn.example.com}
