config:
  import:
    - optional:file:/etc/secret/application-secret.yaml
spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/earseo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

otel:
  propagators:
    - tracecontext
    - b3
    - baggage
management:
  otlp:
    tracing:
      endpoint: http://${NODE_IP:localhost}:4317
      transport: grpc
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true

logging:
  level:
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:debug}
