image:
  tag: v0.1.5
env:
  HOT_SPOT_THRESHOLD: "30"
  STORY_SUMMARY_LIMIT: "3"
  STORY_SUMMARY_THRESHOLD: "3"
  SUMMARY_SCHEDULE_CRON: "0 0 0,6,12,18 * * *"
  OPENAI_MODEL: "gpt-4o-mini"
  OPENAI_TEMPERATURE: "1.2"
  OPENAI_TOP_P: "0.9"
  CORE_SERVER_URL: "http://backend-core:8080"
  DISTANCE_PATH_TO_SPOT: "200"
