name: Spring Boot Integration & Delivery

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  cicd:
    uses: earseo/workflows/.github/workflows/spring-cicd.yaml@feat/springCicd/#1
    secrets: inherit
